# Generated by Django 5.2.8 on 2025-11-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('editorial', models.CharField(blank=True, max_length=200)),
                ('anio_publicacion', models.IntegerField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('num_paginas', models.IntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('copias_disponibles', models.IntegerField(default=1)),
            ],
        ),
    ]
